export enum StudyStatus {
  ACTIVE_NOT_RECRUITING = 'ACTIVE_NOT_RECRUITING',
  COMPLETED = 'COMPLETED',
  ENROLLING_BY_INVITATION = 'ENROLLING_BY_INVITATION',
  NOT_YET_RECRUITING = 'NOT_YET_RECRUITING',
  RECRUITING = 'RECRUITING',
  SUSPENDED = 'SUSPENDED',
  TERMINATED = 'TERMINATED',
  WITHDRAWN = 'WITHDRAWN',
  AVAILABLE = 'AVAILABLE',
  NO_LONGER_AVAILABLE = 'NO_LONGER_AVAILABLE',
  TEMPORARILY_NOT_AVAILABLE = 'TEMPORARILY_NOT_AVAILABLE',
  APPROVED_FOR_MARKETING = 'APPROVED_FOR_MARKETING',
  WITHHELD = 'WITHHELD',
  UNKNOWN = 'UNKNOWN'
}
